{% set name = "kim-api" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://s3.openkim.org/kim-api/{{ name }}-{{ version }}.txz
    sha256: 93673bb8fbc0625791f2ee67915d1672793366d10cabc63e373196862c14f991

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - vim
    - patch
    - tar
    - xz
  run:
    - wget
    - pkg-config
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

test:
  commands:
    - kim-api-collections-management list
    - kim-api-collections-management install system SW_StillingerWeber_1985_Si__MO_405512056662_006

about:
  home: https://openkim.org
  license: LGPL-2.1-or-later
  license_family: OTHER
  license_file: {{ name }}-{{ version }}/LICENSE.LGPL
  summary: 'The Open Knowledgebase of Interatomic Models (OpenKIM) aims to be an online resource for standardized testing, long-term warehousing and easy retrieval of interatomic models and data. '

  description: |
    The Open Knowledgebase of Interatomic Models (OpenKIM) aims to be an
    online resource for standardized testing, long-term warehousing and
    easy retrieval of interatomic models and data.
  doc_url: https://kim-api.readthedocs.io/
  dev_url: https://github.com/openkim/kim-api

extra:
  recipe-maintainers:
    - brendonwaters
    - jan-janssen
    - ellio167
