{% set name = "kim-api" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://s3.openkim.org/kim-api/{{ name }}-{{ version }}.txz
    sha256: 88a5416006c65a2940d82fad49de0885aead05bfa8b59f87d287db5516b9c467
  - path: diff.patch

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - vim
    - patch
    - tar
    - xz
  run:
    - wget

test:
  commands:
    - kim-api-collections-management list

about:
  home: https://openkim.org
  license: CDDL-1.0
  license_family: OTHER
  license_file: {{ name }}-{{ version }}/LICENSE.CDDL
  summary: 'The Open Knowledgebase of Interatomic Models (OpenKIM) aims to be an online resource for standardized testing, long-term warehousing and easy retrieval of interatomic models and data. '

  description: |
    The Open Knowledgebase of Interatomic Models (OpenKIM) aims to be an
    online resource for standardized testing, long-term warehousing and
    easy retrieval of interatomic models and data.
  doc_url: https://kim-api.readthedocs.io/
  dev_url: https://github.com/openkim/kim-api

extra:
  recipe-maintainers:
    - jan-janssen
    - ellio167
